import React from 'react';
import {AbsoluteFill, interpolate, Sequence, spring, useCurrentFrame, useVideoConfig} from 'remotion';

const C={bg:'#09120d',panel:'#111d14',line:'#3e5937',lime:'#c6ff79',white:'#f1f7ed',muted:'#a9bea3',mint:'#83e8ac'};
const sans='Inter,Arial,sans-serif';
const mono='"DejaVu Sans Mono",monospace';

const enter=(f:number,delay=0,travel=28)=>{
  const p=spring({frame:f-delay,fps:30,config:{damping:200},durationInFrames:24});
  return {opacity:p,transform:`translateY(${(1-p)*travel}px)`};
};

const Stage:React.FC<{children:React.ReactNode}>=({children})=>{
  const f=useCurrentFrame();
  const alpha=interpolate(f,[0,12,166,180],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  return <AbsoluteFill style={{opacity:alpha}}>{children}</AbsoluteFill>;
};

const Brand:React.FC=()=> <div style={{position:'absolute',top:42,left:65,display:'flex',alignItems:'center',gap:13,fontFamily:sans,fontWeight:750,fontSize:30,letterSpacing:-2,color:C.white}}><span style={{display:'inline-grid',placeItems:'center',width:36,height:36,borderRadius:12,background:C.lime,color:C.bg,fontSize:27}}>g</span>gap <span style={{fontFamily:mono,fontSize:11,fontWeight:400,letterSpacing:2,color:C.muted,marginLeft:14}}>FREE MICROVM</span></div>;
const Foot:React.FC<{step:string}>=({step})=><div style={{position:'absolute',left:66,right:66,bottom:34,display:'flex',justifyContent:'space-between',fontFamily:mono,fontSize:13,color:'#8da388',letterSpacing:2}}><span>GAP CLOUD / BUILD WITHOUT FRICTION</span><span>{step} / 05</span></div>;
const Eyebrow:React.FC<{children:React.ReactNode}>=({children})=><div style={{fontFamily:mono,fontSize:15,letterSpacing:3,color:C.lime,marginBottom:22}}>{children}</div>;
const Frame:React.FC<{children:React.ReactNode,step:string}>=({children,step})=><Stage><Brand/><div style={{position:'absolute',inset:'110px 65px 82px'}}>{children}</div><Foot step={step}/></Stage>;

const Intro:React.FC=()=>{const f=useCurrentFrame();return <Frame step="01"><div style={{...enter(f,5),marginTop:87}}><Eyebrow>ONE COMMAND. A WHOLE COMPUTER.</Eyebrow><div style={{fontFamily:sans,fontSize:103,lineHeight:1.01,fontWeight:700,letterSpacing:-7,color:C.white}}>From terminal<br/><span style={{color:C.lime}}>to live app.</span></div></div><div style={{...enter(f,53),display:'flex',gap:14,marginTop:48}}>{['1 vCPU','1 GiB','60 min free'].map(x=><div key={x} style={{padding:'12px 20px',borderRadius:30,border:`1px solid ${C.line}`,fontFamily:mono,color:C.muted,fontSize:16}}>{x}</div>)}</div></Frame>};

const Terminal:React.FC<{children:React.ReactNode,width?:number}>=({children,width=1090})=><div style={{width,background:'#08100b',border:`1px solid ${C.line}`,borderRadius:20,overflow:'hidden',boxShadow:'0 30px 90px #0008'}}><div style={{height:49,display:'flex',alignItems:'center',gap:8,padding:'0 20px',background:'#1a291d',borderBottom:`1px solid ${C.line}`}}>{['#d88f78','#dfbc75','#9ec87f'].map(x=><i key={x} style={{width:10,height:10,borderRadius:'50%',background:x}}/>)}<span style={{fontFamily:mono,fontSize:13,color:C.muted,marginLeft:14}}>free@gap — terminal</span></div><div style={{padding:'27px 31px',fontFamily:mono,fontSize:22,lineHeight:1.8,color:C.white}}>{children}</div></div>;

const Connect:React.FC=()=>{const f=useCurrentFrame();const command='ssh -p 2121 free@gap-node-02-u3.vm.elestio.app';const count=Math.min(command.length,Math.max(0,Math.floor((f-20)*.8)));return <Frame step="02"><div style={{...enter(f,4)}}><Eyebrow>01 / CONNECT</Eyebrow><div style={{fontFamily:sans,fontSize:64,fontWeight:700,letterSpacing:-4,lineHeight:1.08,marginBottom:36}}>Your key is your login.</div></div><div style={{...enter(f,14)}}><Terminal><div><span style={{color:C.lime}}>$ </span>{command.slice(0,count)}<span style={{opacity:Math.floor(f/12)%2===0?1:0,color:C.lime}}>▌</span></div><div style={{height:18}}/>{f>84&&<><div style={{color:C.lime}}>GAP / FREE MICROVM</div><div style={{color:C.muted}}>Your workspace is ready · 1 vCPU · 1 GiB</div><div style={{color:C.mint}}>60m 00s left to build</div></>}</Terminal></div></Frame>};

const Preview:React.FC=()=>{const f=useCurrentFrame();const p=spring({frame:f-48,fps:30,config:{damping:200},durationInFrames:28});return <Frame step="03"><div style={{...enter(f,4)}}><Eyebrow>02 / BUILD</Eyebrow><div style={{fontFamily:sans,fontSize:61,fontWeight:700,letterSpacing:-4,marginBottom:30}}>Your work gets a live URL.</div></div><div style={{position:'relative',...enter(f,13)}}><Terminal width={720}><div style={{color:C.muted}}>root@gap:~# <span style={{color:C.white}}>python3 -m http.server 8080</span></div><div style={{color:C.mint}}>Serving your app on port 8080 ✓</div><div style={{height:42}}/><div style={{color:C.muted,fontSize:17}}>PREVIEW  https://…/apps/…/</div><div style={{color:C.muted,fontSize:17}}>BASIC AUTH  free / unique password</div></Terminal><div style={{position:'absolute',left:530,top:105,width:515,height:290,background:'#eef6e8',color:'#1b341d',borderRadius:20,boxShadow:'0 30px 75px #000a',opacity:p,transform:`translateX(${(1-p)*120}px) rotate(2deg)`,padding:20}}><div style={{fontFamily:mono,fontSize:12,color:'#648060',borderBottom:'1px solid #cadcc4',paddingBottom:12}}>●  ●  ● <span style={{float:'right'}}>PRIVATE HTTPS PREVIEW</span></div><div style={{marginTop:16,height:177,borderRadius:9,display:'grid',placeItems:'center',background:'linear-gradient(135deg,#d8edcd,#f8faf5)',fontFamily:sans}}><div style={{fontSize:36,fontWeight:700,letterSpacing:-2,textAlign:'center'}}>Hello, world.<div style={{fontSize:16,fontWeight:400,letterSpacing:0,color:'#60775b'}}>Your app is live.</div></div></div><div style={{fontFamily:mono,fontSize:12,color:'#4b8d4d',marginTop:10}}>● VISIBLE TO YOUR SSH IP</div></div></div></Frame>};

const Claim:React.FC=()=>{const f=useCurrentFrame();return <Frame step="04"><div style={{...enter(f,3)}}><Eyebrow>03 / CLAIM</Eyebrow><div style={{fontFamily:sans,fontSize:66,fontWeight:700,letterSpacing:-4,lineHeight:1.08}}>Keep the same VM.<br/><span style={{color:C.lime}}>Keep every file.</span></div></div><div style={{display:'flex',gap:24,marginTop:59}}>{[{n:'60 min',label:'Build for free',d:28},{n:'24 h',label:'Claim window',d:51},{n:'∞',label:'Your VM after claim',d:74}].map(x=><div key={x.n} style={{...enter(f,x.d),flex:1,height:202,background:C.panel,border:`1px solid ${C.line}`,borderRadius:17,padding:29}}><div style={{fontFamily:sans,fontWeight:720,fontSize:55,letterSpacing:-3,color:C.lime}}>{x.n}</div><div style={{fontFamily:mono,fontSize:16,color:C.muted,marginTop:15}}>{x.label}</div></div>)}</div><div style={{...enter(f,99),fontFamily:mono,fontSize:16,color:C.mint,marginTop:30}}>Verified email only when you decide to claim.</div></Frame>};

const Outro:React.FC=()=>{const f=useCurrentFrame();const border=interpolate(f,[45,100],[.2,1],{extrapolateRight:'clamp'});return <Frame step="05"><div style={{...enter(f,7),marginTop:85}}><Eyebrow>YOUR NEXT IDEA STARTS HERE</Eyebrow><div style={{fontFamily:sans,fontSize:93,lineHeight:1.03,fontWeight:730,letterSpacing:-6}}>One command.<br/><span style={{color:C.lime}}>Your own computer.</span></div></div><div style={{...enter(f,52),display:'inline-flex',alignItems:'center',gap:18,marginTop:58,padding:'19px 26px',borderRadius:14,background:C.panel,border:`2px solid rgba(198,255,121,${border})`,fontFamily:mono,fontSize:22,color:C.white}}><span style={{color:C.lime}}>$</span> ssh -p 2121 free@gap-node-02-u3.vm.elestio.app</div></Frame>};

export const FreeVmMotion:React.FC=()=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const glowX=interpolate(frame,[0,900],[950,240]);return <AbsoluteFill style={{background:C.bg,color:C.white,overflow:'hidden'}}><div style={{position:'absolute',inset:0,backgroundImage:'linear-gradient(#273c291e 1px, transparent 1px),linear-gradient(90deg,#273c291e 1px,transparent 1px)',backgroundSize:'52px 52px'}}/><div style={{position:'absolute',left:glowX,top:150,width:620,height:620,borderRadius:'50%',filter:'blur(100px)',background:'#396a2d66'}}/><Sequence from={0} durationInFrames={6*fps} premountFor={fps}><Intro/></Sequence><Sequence from={6*fps} durationInFrames={6*fps} premountFor={fps}><Connect/></Sequence><Sequence from={12*fps} durationInFrames={6*fps} premountFor={fps}><Preview/></Sequence><Sequence from={18*fps} durationInFrames={6*fps} premountFor={fps}><Claim/></Sequence><Sequence from={24*fps} durationInFrames={6*fps} premountFor={fps}><Outro/></Sequence></AbsoluteFill>};
