"""Opt-in PostgreSQL authority for isolated HA validation, not production wiring.

Business operations are inherited unchanged. Every transaction takes the same
DB-wide advisory lock, preserving SQLite BEGIN IMMEDIATE serialization across
controller processes. This lock is NOT fencing between divergent primaries.
"""
from contextlib import contextmanager
from decimal import Decimal
import re
import time
from authority import Authority, Failure, identifier


class Row(dict):
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def row_factory(cursor):
    names=[column.name for column in cursor.description] if cursor.description else []
    # PostgreSQL SUM(bigint) returns NUMERIC; preserve the integer contract.
    return lambda values:Row(zip(names,(int(v) if isinstance(v,Decimal) and v==v.to_integral_value() else v for v in values)))


def statement(sql):
    # Only the internal authority SQL dialect, never caller-supplied SQL.
    if sql == "SELECT 1 FROM sqlite_master WHERE type='table' AND name='verified_emails'":
        return "SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name='verified_emails'"
    ignored=sql.startswith('INSERT OR IGNORE INTO ')
    if ignored:sql=sql.replace('INSERT OR IGNORE INTO ','INSERT INTO ',1)+' ON CONFLICT DO NOTHING'
    replacements={
        'INSERT OR REPLACE INTO customer_suspensions VALUES(?,?,?,?,?,?)':
            'INSERT INTO customer_suspensions VALUES(?,?,?,?,?,?) ON CONFLICT(subject) DO UPDATE SET active=excluded.active,revision=excluded.revision,reason=excluded.reason,hold_until=excluded.hold_until,updated=excluded.updated',
        'INSERT OR REPLACE INTO detached_members VALUES(?,?)':
            'INSERT INTO detached_members VALUES(?,?) ON CONFLICT(agent) DO UPDATE SET customer=excluded.customer',
    }
    sql=replacements.get(sql,sql)
    if 'INSERT OR ' in sql:raise ValueError('unsupported_authority_sql')
    # Leave quoted literals intact; parameters always travel separately.
    parts=re.split("('(?:[^']|'')*')",sql)
    for i in range(0,len(parts),2):
        part=parts[i]
        if sql.lstrip().startswith('CREATE TABLE'):
            part=part.replace('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
            part=re.sub(r'\bINTEGER\b','BIGINT',part)
        parts[i]=part.replace('?', '%s')
    return ''.join(parts)


class Connection:
    def __init__(self, connection):self.connection=connection
    def execute(self, sql, parameters=()):
        return self.connection.execute(statement(sql),parameters or None)


class PostgresAuthority(Authority):
    def __init__(self, dsn, operator, clock=time.time):
        # DSN can list several hosts. No automatic mutation retries: callers
        # must reuse the same request ID after an ambiguous commit response.
        self.dsn=dsn
        self.operator=identifier(operator)
        self.clock=clock
        self.initialize_schema()

    @contextmanager
    def db(self):
        import psycopg
        try:
            with psycopg.connect(self.dsn,autocommit=True,row_factory=row_factory,
                                 connect_timeout=3,target_session_attrs='read-write') as conn:
                with conn.transaction():
                    conn.execute("SET LOCAL transaction_isolation='read committed'")
                    conn.execute("SET LOCAL synchronous_commit='on'")
                    conn.execute("SET LOCAL statement_timeout='5s'")
                    conn.execute("SET LOCAL lock_timeout='5s'")
                    conn.execute("SET LOCAL idle_in_transaction_session_timeout='10s'")
                    conn.execute('SELECT pg_advisory_xact_lock(1195462736)')
                    yield Connection(conn)
        except psycopg.Error:
            # Neither DSN, SQL values nor server diagnostics reach API callers.
            raise Failure('control_database_unavailable',503) from None
