#!/usr/bin/env python3
"""Install public fleet SSH routing metadata in a worker runner config.

Private relay keys are generated by the gateway on first start and never leave
the worker. This script changes only the free_vm section of runner.json.
"""
import argparse
import json
import os
from pathlib import Path
import re
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('config', type=Path)
    parser.add_argument('--node-id', required=True)
    parser.add_argument('--fleet-public-key', required=True)
    parser.add_argument('--peer', action='append', nargs=3,
                        metavar=('NODE_ID', 'HOST', 'HOST_KEY'), default=[])
    args = parser.parse_args()
    if args.node_id not in ('node-01', 'node-02', 'node-03'):
        parser.error('invalid node ID')
    if not re.fullmatch(r'[0-9a-f]{64}', args.fleet_public_key):
        parser.error('invalid fleet public key')
    peers = {}
    for node, host, host_key in args.peer:
        if node in peers or node not in ('node-01', 'node-02', 'node-03') or node == args.node_id:
            parser.error('invalid or duplicate peer')
        if not re.fullmatch(r'[a-z0-9.-]{1,253}', host):
            parser.error('invalid peer hostname')
        if not re.fullmatch(r'ssh-ed25519 [A-Za-z0-9+/=]{60,128}', host_key):
            parser.error('invalid peer host key')
        peers[node] = {'host': host, 'host_key': host_key}
    if set(peers) != {'node-01', 'node-02', 'node-03'} - {args.node_id}:
        parser.error('both other fleet nodes are required')
    stat = args.config.stat()
    config = json.loads(args.config.read_text())
    if config.get('free_vm', {}).get('enabled') is not True:
        parser.error('free VM gateway is not enabled')
    config['free_vm'].update(node_id=args.node_id, peers=peers,
                             fleet_public_key=args.fleet_public_key)
    encoded = (json.dumps(config, sort_keys=True, indent=2) + '\n').encode()
    descriptor, pending = tempfile.mkstemp(prefix='.runner-relay-', dir=args.config.parent)
    try:
        os.fchmod(descriptor, stat.st_mode & 0o777)
        os.fchown(descriptor, stat.st_uid, stat.st_gid)
        with os.fdopen(descriptor, 'wb') as stream:
            stream.write(encoded)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(pending, args.config)
    finally:
        if os.path.exists(pending):
            os.unlink(pending)


if __name__ == '__main__':
    main()
